version: '3.7'

services:
  gateway:
    build:
      context: ../gateway  
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - web
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local`)"  # Expose dashboard

  order:
    build: ../services/order
    container_name: order
    networks:
      - web
    ports:
      - "3002:80"  # Map container port 80 to host port 3002
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.order.rule=Host(`order.local`) && Path(`/order`)"  # Correct path routing
      - "traefik.http.services.order.loadbalancer.server.port=80"  # Internal service port

  cargo:
    build: ../services/cargo
    container_name: cargo
    networks:
      - web
    ports:
      - "3001:80"  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cargo.rule=Host(`cargo.local`) && Path(`/cargo`)"  
      - "traefik.http.services.cargo.loadbalancer.server.port=80" 

  tracking:
    build: ../services/tracking
    container_name: tracking
    networks:
      - web
    ports:
      - "8000:80"  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tracking.rule=Host(`tracking.local`) && Path(`/tracking`)"  # Correct path routing
      - "traefik.http.services.tracking.loadbalancer.server.port=80"  # Internal service port

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Default RabbitMQ port for communication
      - "15672:15672"  # Management UI
    networks:
      - web
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

networks:
  web:
    driver: bridge

volumes:
  rabbitmq-data:
