version: '3.8'

services:
  order:
    build:
      context: ../services/order
      dockerfile: Dockerfile
    container_name: order
    volumes:
      - ../services/order:/app
    ports:
      - "3004:3004"  
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - ../services/order/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.order.rule=Host(`order.localhost`)"   
      - "traefik.http.services.order.loadbalancer.server.port=3004"  
    networks:
      - traefik

  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
        

networks:
  traefik:
    external: true  
