version: '3.8'

services:
  order:
    build:
      context: ../services/order
      dockerfile: Dockerfile
    container_name: order
    volumes:
      - ../services/order:/app
    ports:
      - "3004:3004" 
    environment:
      - DATABASE_URL=${DATABASE_URL_1}
    env_file:
      - ../services/order/.env
    labels:
      - "traefik.enable=true" 
      - "traefik.http.services.order.loadbalancer.server.port=3004"
      - "traefik.http.routers.order.rule=Host(`order.localhost`) && (PathPrefix(`/docs`) || PathPrefix(`/tracking`) || PathPrefix(`/orders`))"
    networks:
      - traefik
  
  # product:
  #   build:
  #     context: ../services/product
  #     dockerfile: Dockerfile
  #   container_name: product
  #   volumes:
  #     - ../services/product:/app
  #   ports:
  #     - "3005:3005" 
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL_1}
  #   env_file:
  #     - ../services/product/.env
  #   labels:
  #     - "traefik.enable=true" 
  #     - "traefik.http.services.product.loadbalancer.server.port=3005"
  #     - "traefik.http.routers.product.rule=Host(`product.localhost`) && (PathPrefix(`/docs`) || PathPrefix(`/products`))"  
  #   networks:
  #     - traefik

  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672" 
      - "15672:15672" 
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - traefik
    labels:
      - "traefik.enable=false" 

networks:
  traefik:
    external: true
