version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: driver-api
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
    volumes:
      - ./logs:/app/logs
    networks:
      - driver-network

networks:
  driver-network:
    driver: bridge